# MySQL-specific code to create tables for auction hub.

# as_hub contains details about this auction hub installation.
# A single hub serves multiple auction sites connected to it.
CREATE TABLE as_hub (
  uuid       CHAR(36)         NOT NULL,     # Random UUID identifying this hub.
  hub_name  VARCHAR(64)       NOT NULL,     # Name for this hub.
  uri        VARCHAR(256)                   # URI at which this hub is available to servers and other hubs.
);

# as_currencies contains currencies supported by auction hub.
CREATE TABLE ah_currencies (
  id         INTEGER,                       # Currency id.
  name       VARCHAR(3)       NOT NULL,     # USD, CAD, NZD, etc.
  PRIMARY KEY (id)
);


# ah_sites contains participating auction sites that this hub serves.
CREATE TABLE ah_sites (
  uuid                  CHAR(36)     NOT NULL,   # Site UUID.
  name                  VARCHAR(64)  NOT NULL,   # Site name.
  uri                   VARCHAR(256) NOT NULL,   # Site URI.
  status                INTEGER,                 # Site status.
  PRIMARY KEY (uuid)
);


# ah_local_auctions contains active auctions originated on sites served by this hub.
# Note that as auctions are closed, they are moved to ah_closed_auctions to keep this table small.
CREATE TABLE ah_local_auctions (
  uuid                  CHAR(36)     NOT NULL,  # Random UUID of the auction, generated by the site.
  site_uuid             CHAR(36)     NOT NULL,  # Site UUID.
  seller_uuid           CHAR(36)     NOT NULL,  # Seller UUID.
  name                  VARCHAR(256) NOT NULL,  # Name of the auction item.
  description           TEXT         NOT NULL,  # Description of the auction item.
  image_uri             VARCHAR(256),           # Image URI.
  created_timestamp     CHAR(19)     NOT NULL,  # Creation timestamp in format like "2016-04-08 15:00:10".
  close_timestamp       CHAR(19)     NOT NULL,  # Close timestamp in format like "2016-04-15 15:00:10".
  currency_id           INTEGER      NOT NULL,  # Currency id.
  reserve_price         NUMERIC(15,2),          # Reserve price of the auction.
  current_price         NUMERIC(15,2),          # Current price of the auction.
  status                INTEGER,                # Status of the auction.
  PRIMARY KEY (uuid)
);


# ah_remote_auctions contains active auctions originated on remote hubs.
CREATE TABLE ah_remote_auctions (
  uuid                  CHAR(36)     NOT NULL,  # Random UUID of the auction, generated by the site.
  site_uuid             CHAR(36)     NOT NULL,  # Originating site UUID.
  hub_uuid              CHAR(36)     NOT NULL,  # Hub UUID that serves the originating site.
  seller_uuid           CHAR(36)     NOT NULL,  # Seller UUID.
  name                  VARCHAR(256) NOT NULL,  # Name of the auction item.
  description           TEXT         NOT NULL,  # Description of the auction item.
  image_uri             VARCHAR(256),           # Image URI.
  created_timestamp     CHAR(19)     NOT NULL,  # Creation timestamp in format like "2016-04-08 15:00:10".
  close_timestamp       CHAR(19)     NOT NULL,  # Close timestamp in format like "2016-04-15 15:00:10".
  currency_id           INTEGER      NOT NULL,  # Currency id.
  reserve_price         NUMERIC(15,2),          # Reserve price of the auction.
  current_price         NUMERIC(15,2),          # Current price of the auction.
  status                INTEGER,                # Status of the auction.
  PRIMARY KEY (uuid)
);


# ah_closed_auctions contains closed auctions originated on sites served by this hub.
CREATE TABLE as_closed_auctions (
  uuid                  CHAR(36)     NOT NULL,  # Random UUID of the auction, generated by the site.
  site_uuid             CHAR(36)     NOT NULL,  # Originating site UUID.
  seller_uuid           CHAR(36)     NOT NULL,  # Seller UUID.
  name                  VARCHAR(256) NOT NULL,  # Name of the auction item.
  description           TEXT         NOT NULL,  # Description of the auction item.
  image_uri             VARCHAR(256),           # Image URI.
  created_timestamp     CHAR(19)     NOT NULL,  # Creation timestamp in format like "2016-04-08 15:00:10".
  close_timestamp       CHAR(19)     NOT NULL,  # Close timestamp in format like "2016-04-15 15:00:10".
  currency_id           INTEGER      NOT NULL,  # Currency id.
  reserve_price         NUMERIC(15,2),          # Reserve price of the auction.
  current_price         NUMERIC(15,2),          # Current price of the auction.
  status                INTEGER,                # Status of the auction.
  PRIMARY KEY (uuid)
);


# ah_bids contains bids created by local users on local and remote items.
CREATE TABLE ah_bids (
  uuid                  CHAR(36)     NOT NULL,   # Random UUID of the bid.
  site_uuid             CHAR(36),                # Site UUID for the auction item.
  auction_uuid          CHAR(36)     NOT NULL,   # UUID of the auction item.
  max_price             NUMERIC(15,2),           # Max price of the pid.
  user_uuid             CHAR(36)     NOT NULL,   # User UUID who placed the bid.
  created_timestamp     CHAR(19)     NOT NULL,   # Bid creation timestamp in format like "2016-04-08 15:01:10".
  status                INTEGER,                 # Status of the bid.
  PRIMARY KEY (uuid)
);


# ah_closed_bids contains closed bids created by local users on local and remote items.
CREATE TABLE ah_closed_bids (
  uuid                  CHAR(36)     NOT NULL,   # Random UUID of the bid.
  site_uuid             CHAR(36),                # Site UUID for the auction item.
  auction_uuid          CHAR(36)     NOT NULL,   # UUID of the auction item.
  max_price             NUMERIC(15,2),           # Max price of the pid.
  user_uuid             CHAR(36)     NOT NULL,   # User UUID who placed the bid.
  created_timestamp     CHAR(19)     NOT NULL,   # Bid creation timestamp in format like "2016-04-08 15:01:10".
  status                INTEGER,                 # Status of the bid.
  PRIMARY KEY (uuid)
);
